---
title: "Classification ML"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE, message=FALSE, warning=FALSE,
                      fig.width=7, fig.height=3, fig.align = "center")
options(digits=3)
library(tidyverse)
library(tidymodels)
library(readr)
PPH <- read_csv("PPH_newcols.csv")
```

### Create another column for severe morbidity
```{r}
#the cdc 21 severity
PPH[126:146]

#SMM is severe maternal morbidity according tO cdc's definition, Y means severe, N means not severe

PPH_ml <- PPH %>% mutate(SMM = ifelse(!!rowSums(PPH[126:146]), "Y", "N")) %>% select(age, died, race, zipinc_qrtl, obesity, diabetes, gh , mg , pp , pa , pl, hu , SMM)

```

### CART

```{r}
#partition the dataset into train data and test data
set.seed(4747)
PPH_split <- initial_split(PPH_ml, prop = 0.75, strata = SMM)
PPH_train <- training(PPH_split)
PPH_test <- testing(PPH_split)
```


```{r}
# recipe
PPH_cart_recipe <- recipe(SMM ~ . , data = PPH_train) %>%
  step_mutate(race = as.factor(race), zipinc_qrtl = as.factor(zipinc_qrtl)) %>%
  step_dummy(race) %>%
  step_dummy(zipinc_qrtl)

summary(PPH_cart_recipe)

```

```{r}
PPH_cart <- decision_tree() %>%
  set_engine("rpart") %>%
  set_mode("classification")

PPH_cart

PPH_cart_wflow <- workflow() %>%
  add_model(PPH_cart) %>%
  add_recipe(PPH_cart_recipe)

PPH_cart_wflow

PPH_cart_fit <- PPH_cart_wflow %>%
  fit(data = PPH_train)

PPH_cart_fit %>%
  predict(new_data = PPH_train) %>%
  cbind(PPH_train) %>%
  select(.pred_class, SMM) %>%
  table()


library(rpart.plot)
PPH_cart_plot <- 
  PPH_cart_fit %>%
  extract_fit_parsnip()

rpart.plot(
  PPH_cart_plot$fit,
  roundint = FALSE)
```


Model 2: Random Forest. Tuning parameters: mtry and number of trees.

```{r}
# recipe
PPH_rf_recipe <-
recipe(SMM ~. , data = PPH_train) 

summary(PPH_rf_recipe)

# variable selection

#model
PPH_rf <- rand_forest(mtry = tune(),
                           trees = tune()) %>%
  set_engine("ranger", importance = "permutation") %>%
  set_mode("classification")


# workflow
PPH_rf_wflow <- workflow() %>%
add_model(PPH_rf) %>%
add_recipe(PPH_rf_recipe)

#create folds
set.seed(234)
PPH_folds <- vfold_cv(PPH_train, v = 5)

#grid for tuning mtry and trees
rf_grid <- grid_regular(mtry(range = c(2,11)),
                             trees(range = c(1,400)),
                             levels = 5)
#tune
PPH_rf_tune <- 
  PPH_rf_wflow %>%
  tune_grid(resamples = PPH_folds,
            grid = rf_grid)

PPH_rf_tune %>% collect_metrics() %>%
filter(.metric == "accuracy")

PPH_rf_best <- finalize_model(
  PPH_rf,
  select_best(PPH_rf_tune, "accuracy"))

PPH_rf_best
```
