---
title: "PPH data"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
NIS_2018_Core <- read_csv("~/datathon/NIS_2018_Core.csv") %>%
  mutate(key = round(key_nis))
NIS_2018_Severity <- read_csv("~/datathon/NIS_2018_Severity.csv") %>%
  mutate(key = round(key_nis))

```

### DO NOT RUN THE CHUNK BELOW 
```{r}
# do all keys in Core match keys in Severity?
setdiff(NIS_2018_Severity$key, NIS_2018_Core$key) #returns 0
setdiff(NIS_2018_Core$key, NIS_2018_Severity$key) #returns 181515 keys that are in Core but not Severity

#pick a key returned from the above line: 51245142
a <- NIS_2018_Core %>% filter(key == 51245142) #1 observation
b <- NIS_2018_Severity %>% filter(key == 51245142)#0 observation
#oops then the keys in Core and Severity don't exactly match, severity might have repeated rows 

#see if severity has repeated keys
c <- NIS_2018_Severity %>% group_by(key) %>% summarize(count = n()) #has 6923983 rows(aka distinct keys), but Severity has 7105498 rows, 181515 rows are missing
c %>% filter(count == 2) #there are 181515 keys that showed up twice

#for example, 51149147 is counted twice, let's look it up in Core and Severity
bug_Severity <- NIS_2018_Severity %>% filter(key == 51149147)
View(bug_Severity)
#it turns out 51149148 is transformed to 51149148
e <- NIS_2018_Severity %>% filter(key_nis == 51149147)
e_2 <- NIS_2018_Severity %>% filter(key == 51149147)
e_2 %>% mutate(num_key = as.numeric(key_nis))
```

```{r}
#filter out all obs that has O72 in dianosis
icd_2018 <- sprintf("i10_dx%d",seq(1:40)) #2018 has 10_dx1-40
PPH_Core_2018 <- NIS_2018_Core %>% 
  filter_at(icd_2018, any_vars(.%in% c("O720","O721", "O722", "O723")))
count(PPH_Core_2018) #30204 patients diagonsed with PPH in 2018

PPH_2018 <- left_join(PPH_Core_2018, NIS_2018_Severity, by = "key") %>% select(-c("key_nis.x","hosp_nis.y"))

```

```{r}
#same for 2017
icd_2017 <- sprintf("i10_dx%d",seq(1:40)) 
NIS_2017_Core <- read_csv("~/datathon/NIS_2017_Core.csv") %>%
  mutate(key = round(key_nis))
NIS_2017_Severity <- read_csv("~/datathon/NIS_2017_Severity.csv") %>%
  mutate(key = round(key_nis))
PPH_Core_2017 <- NIS_2017_Core %>% 
  filter_at(icd_2017, any_vars(.%in% c("O720","O721", "O722", "O723")))
count(PPH_Core_2017) #28375 patients diagonsed with PPH in 2017

PPH_2017 <- left_join(PPH_Core_2017, NIS_2017_Severity, by = "key") %>% select(-c("key_nis.x","hosp_nis.y","dxver","prver")) #the dxver and prver in 2017 are all 10,no these two columns in years after

colnames(PPH_2017) == colnames(PPH_2018) #quick check - now PPH2017 and 2018 have same columns

#same process for 2019
icd_2019 <- sprintf("i10_dx%d",seq(1:40)) 
NIS_2019_Core <- read_csv("~/datathon/NIS_2019_Core.csv") %>%
  mutate(key = round(key_nis))
NIS_2019_Severity <- read_csv("~/datathon/NIS_2019_Severity.csv") %>%
  mutate(key = round(key_nis))
PPH_Core_2019 <- NIS_2019_Core %>% 
  filter_at(icd_2019, any_vars(.%in% c("O720","O721", "O722", "O723")))
count(PPH_Core_2019) #32416 patients diagonsed with PPH in 2019

PPH_2019 <- left_join(PPH_Core_2019, NIS_2019_Severity, by = "key") %>% select(-c("key_nis.x","hosp_nis.y"))
setdiff(colnames(PPH_2019),colnames(PPH_2018))
# 6 new variables in 2019 "i10_birth", "i10_delivery", "i10_injury"     "i10_multinjury" , "i10_serviceline" ,"pclass_orproc", drop them for now
PPH_2019 <- PPH_2019 %>% select(-c("i10_birth", "i10_delivery", "i10_injury",    "i10_multinjury" , "i10_serviceline" ,"pclass_orproc"))

#same for 2016, only that 2016 has fewer i10_dx and i10_pr and prday
icd_2016 <- sprintf("i10_dx%d",seq(1:30)) 
NIS_2016_Core <- read_csv("~/datathon/NIS_2016_Core.csv") %>%
  mutate(key = round(key_nis))
NIS_2017_Severity <- read_csv("~/datathon/NIS_2016_Severity.csv") %>%
  mutate(key = round(key_nis))
PPH_Core_2016 <- NIS_2016_Core %>% 
  filter_at(icd_2016, any_vars(.%in% c("O720","O721", "O722", "O723")))
count(PPH_Core_2016) #25688 patients diagonsed with PPH in 2017

PPH_2016 <- left_join(PPH_Core_2016, NIS_2017_Severity, by = "key") %>% select(-c("key_nis.x","hosp_nis.y"))
setdiff(colnames(PPH_2019),colnames(PPH_2016))
# need to add 3*10 columns with the following names(all values set to NA) #"i10_dx31","i10_dx32","i10_dx33","i10_dx34", "i10_dx35","i10_dx36","i10_dx37", "i10_dx38","i10_dx39","i10_dx40",
#"i10_pr16", "i10_pr17","i10_pr18","i10_pr19","i10_pr20","i10_pr21","i10_pr22","i10_pr23", "i10_pr24","i10_pr25",
#"prday16" , "prday17",  "prday18" , "prday19" ,
#"prday20" ,"prday21", "prday22","prday23", "prday24", "prday25"
setdiff(colnames(PPH_2016),colnames(PPH_2019))
#the variables that 2016 has but no longer exists for later years
#"dxver""i10_ecause1" "i10_ecause2" "i10_ecause3" "i10_ecause4" "i10_necause" "prver"
#remove them for now
PPH_2016 <- PPH_2016 %>% 
  select(-c("dxver","i10_ecause1","i10_ecause2", "i10_ecause3" ,"i10_ecause4" ,"i10_necause","prver")) %>% 
  add_column("i10_dx31" = NA,"i10_dx32" = NA,"i10_dx33" = NA,"i10_dx34"= NA, "i10_dx35"= NA,"i10_dx36"= NA,"i10_dx37"= NA, "i10_dx38"= NA,"i10_dx39"= NA,"i10_dx40"= NA, .after = "i10_dx30") %>%
  add_column("i10_pr16" = NA, "i10_pr17" = NA,"i10_pr18" = NA,"i10_pr19"= NA,"i10_pr20"= NA,"i10_pr21"= NA,"i10_pr22"= NA,"i10_pr23"= NA, "i10_pr24"= NA,"i10_pr25"= NA, .after = "i10_pr15") %>%
  add_column("prday16"= NA , "prday17"= NA,  "prday18"= NA , "prday19" = NA,
"prday20" = NA,"prday21"= NA, "prday22"= NA,"prday23"= NA, "prday24"= NA, "prday25"= NA, .after = "prday15")

#check if all datasets has same column names
check <- cbind(as.data.frame(colnames(PPH_2016)),as.data.frame(colnames(PPH_2017)),as.data.frame(colnames(PPH_2018)), as.data.frame(colnames(PPH_2019)))
check %>% filter(colnames(PPH_2016) == colnames(PPH_2018) | 
                 colnames(PPH_2016) == colnames(PPH_2017) |
                 colnames(PPH_2016) == colnames(PPH_2019) ) #returns all the 125 rows! so now all 4 datasets have same variables in same order


#final,big dataset combining 2016-2019 year
PPH <- rbind(PPH_2016, PPH_2017, PPH_2018, PPH_2019)

```


```

### ignore the chunk below:
```{r}
#left_join
trial_core_2018 <- NIS_2018_Core %>% head(10)
trial_severity_2018 <- NIS_2018_Severity %>% head(20) %>% mutate(key = as.integer(as.character(key_nis)))

inner_join(trial_core_2018, trial_severity_2018, by = c("key_nis" = "key"))

trial_core_2018_int <- trial_core_2018

trial_severity_2018_int <- trial_severity_2018 %>% 
  mutate(key = as.integer(key_nis))

trial_complete_2018 <- left_join(trial_core_2018_int, trial_severity_2018_int, by = "key") 
```